name: maid_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0' # <-- Corrected syntax

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.1
  provider: ^6.1.2
  intl: 0.20.2
  cupertino_icons: ^1.0.8
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  geolocator: ^12.0.0  
  package_info_plus: ^8.3.0
  url_launcher: ^6.2.6
  font_awesome_flutter: ^10.7.0 
  image_picker: ^1.0.7
  image_cropper: ^7.0.0
  crop_your_image: ^1.0.3
  image: ^4.1.7
  flutter_spinkit: ^5.2.0
  shared_preferences: ^2.2.2

# <-- Corrected version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Phetsarath
      fonts:
        - asset: fonts/Phetsarath-Regular.ttf